[package]
name = "manufacturing-kernel-adapter"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
fj.workspace = true
fj-core.workspace = true
fj-math.workspace = true
